# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Test New Blog
subtitle: '这是一个测试博客，用于测试Hexo的功能'
author: 李先泽
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://lzq530.icu
root: /

theme: butterfly
butterfly:
  cdn: false

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
